# foreground              #CDD6F4
# background              #11111b
# selection_foreground    #FFFFFF
# selection_background    #222233

# cursor                  #FFFFFF
# cursor_text_color       #11111b

# active_border_color     #B4BEFE
# inactive_border_color   #6C7086

# active_tab_foreground   #CBA6F7
# active_tab_background   #11111b
# inactive_tab_foreground #CDD6F4
# inactive_tab_background #11111b
# tab_bar_background      none

# color0 #11111b
# color8 #333344
# The basic colors
foreground              #CDD6F4
background              #1B2C3D
selection_foreground    #11111a
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #08080C

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #CBA6F7
active_tab_background   #1B2C3D
inactive_tab_foreground #CDD6F4
inactive_tab_background #1B2C3D
tab_bar_background      none

# Colors for marks (marked text in the terminal)
mark1_foreground #08080C
mark1_background #B4BEFE
mark2_foreground #08080C
mark2_background #CBA6F7
mark3_foreground #08080C
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
