# Fonts
# font_family JetBrainsMono Nerd Font Mono
font_family Hurmit Nerd Font


bold_font auto
italic_font auto
bold_italic_font auto
font_size 13
cursor_blink_interval 0.5 ease-in-out

# font_family MonoLisa
# font_features MonoLisa +liga +calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09
# font_family JetBrainsMono Nerd Font Mono
# font_features JetBrainsMonoNerdFont-Regular +liga
# font_features HurmitNerdFont-Regular +liga +calt


# hide_window_decorations yes
scrollback_indicator_opacity 0

window_padding_width 2 5 10
window_margin_width 2 5 10

shell_integration enabled

# include current-theme.conf
include mocha.conf
# END_KITTY_THEME
